language: java
before_script:
- openssl aes-256-cbc -K $encrypted_abed99774422_key -iv $encrypted_abed99774422_iv
  -in client-secret.json.enc -out client-secret.json -d
script:
- mvn test -B
- mvn appengine:update -Dappengine.additionalParams="--service_account_json_key_file=client-secret.json"
